POST https://reqres.in/api/login
Content-Type: application/json

{
    "email": "eve.holt@reqres.in",
    "password": "asdasdasdasd"
}
### 
POST https://reqres.in/api/register
Content-Type: application/json

{     
    "email": "eve.holt@reqres.in",
    "password": "sdsd"
}
### 
GET https://reqres.in/api/login